version: 0.2

env:
  variables:
    ENVIRONMENT: "production"
    API_URL: "https://api.example.com"

phases:
  install:
    runtime-versions:
      nodejs: 14 # Specify the Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build tasks..."
      - npm run lint # Example: Linting your code
      - npm run test # Example: Running tests
  build:
    commands:
      - echo "Building the application..."
      - npm run build # Example: Building your app
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Packaging the application for deployment..."
      - npm run package # Example: Packaging the build artifacts

artifacts:
  files:
    - "**/*" # Include all files in the build directory
  base-directory: "build/" # Specify the directory to start collecting files

cache:
  paths:
    - "node_modules/**/*" # Cache node_modules to speed up future builds

reports:
  unit-test-reports:
    files:
      - "reports/test-results.xml" # Example: Uploading test reports
    file-format: JUNITXML
# Optional: Define additional commands for cleanup or deployment
